<?php
session_start();
require 'db.php';

// Ensure user is logged in
if (!isset($_SESSION['user'])) {
    header("Location: login.php");
    exit();
}

// Get session user info
$userId     = $_SESSION['user']['user_id'];
$canInsert  = $_SESSION['user']['can_insert'] ?? 0;
$canEdit    = $_SESSION['user']['can_edit'] ?? 0;
$canDelete  = $_SESSION['user']['can_delete'] ?? 0;

$editOrg = null;
$msg = "";

// ----------------------
// Handle Add / Update
// ----------------------
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $orgCode  = $_POST['ORG_CODE'] ?? ''; // empty when adding new
    $name     = trim($_POST['ORGANIZATION_NAME']);
    $address  = trim($_POST['ORGANIZATION_ADDRESS']);
    $contact  = trim($_POST['ORGANIZATION_CONTACT']);
    $auth     = $_POST['AUTHORIZED_STARUS'] ?? 'Y'; // default Y

    if ($name) {
        if ($orgCode) {
            // Update existing organization
            if ($canEdit) {
                $stmt = $pdo->prepare("
                    UPDATE organization_info
                    SET ORGANIZATION_NAME = :name,
                        ORGANIZATION_ADDRESS = :address,
                        ORGANIZATION_CONTACT = :contact,
                        AUTHORIZED_STARUS = :auth,
                        EDIT_USER = :user,
                        EDIT_DATE = CURDATE()
                    WHERE ORG_CODE = :org
                ");
                $stmt->execute([
                    'name'    => $name,
                    'address' => $address,
                    'contact' => $contact,
                    'auth'    => $auth,
                    'user'    => $userId,
                    'org'     => $orgCode
                ]);
                $msg = "✅ Organization updated successfully.";
            } else {
                $msg = "❌ You don't have permission to edit.";
            }
        } else {
            // Insert new organization (ORG_CODE auto-generated by trigger)
            if ($canInsert) {
                $stmt = $pdo->prepare("
                    INSERT INTO organization_info 
                    (ORGANIZATION_NAME, ORGANIZATION_ADDRESS, ORGANIZATION_CONTACT, 
                     AUTHORIZED_STARUS, ENTRY_USER, ENTRY_DATE)
                    VALUES 
                    (:name, :address, :contact, :auth, :user, CURDATE())
                ");
                $stmt->execute([
                    'name'    => $name,
                    'address' => $address,
                    'contact' => $contact,
                    'auth'    => $auth,
                    'user'    => $userId
                ]);
                $msg = "✅ Organization added successfully (Code auto-generated).";
            } else {
                $msg = "❌ You don't have permission to add new data.";
            }
        }
    } else {
        $msg = "⚠️ Organization Name is required.";
    }
}

// ----------------------
// Handle Edit Request
// ----------------------
if (isset($_GET['edit']) && $canEdit) {
    $stmt = $pdo->prepare("SELECT * FROM organization_info WHERE ORG_CODE = :org");
    $stmt->execute(['org' => $_GET['edit']]);
    $editOrg = $stmt->fetch();
}

// ----------------------
// Handle Delete Request (Soft Delete)
// ----------------------
if (isset($_GET['delete']) && $canDelete) {
    $stmt = $pdo->prepare("
        UPDATE organization_info 
        SET DELETE_USER = :user, DELETE_DATE = CURDATE()
        WHERE ORG_CODE = :org
    ");
    $stmt->execute(['user' => $userId, 'org' => $_GET['delete']]);
    $msg = "⚠️ Organization marked as deleted.";
}

// ----------------------
// Fetch All Organizations
// ----------------------
$stmt = $pdo->query("SELECT * FROM organization_info WHERE DELETE_DATE IS NULL ORDER BY ORG_CODE");
$organizations = $stmt->fetchAll();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Organization Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">

<?php include 'header.php'; ?>

<main class="flex-grow-1 container py-4">
    <h3>Organization Management</h3>

    <?php if ($msg): ?>
        <div class="alert alert-info"><?= htmlspecialchars($msg) ?></div>
    <?php endif; ?>

    <!-- Organization Form -->
    <?php if ($canInsert || $editOrg): ?>
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <form method="post">
                <?php if ($editOrg): ?>
                    <input type="hidden" name="ORG_CODE" value="<?= htmlspecialchars($editOrg['ORG_CODE']) ?>">
                <?php endif; ?>

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label>Organization Name <span class="text-danger">*</span></label>
                        <input type="text" name="ORGANIZATION_NAME" class="form-control" required
                               value="<?= htmlspecialchars($editOrg['ORGANIZATION_NAME'] ?? '') ?>">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label>Authorized Status</label>
                        <select name="AUTHORIZED_STARUS" class="form-select">
                            <option value="Y" <?= (!isset($editOrg['AUTHORIZED_STARUS']) || $editOrg['AUTHORIZED_STARUS'] == 'Y') ? 'selected' : '' ?>>Yes</option>
                            <option value="N" <?= (isset($editOrg['AUTHORIZED_STARUS']) && $editOrg['AUTHORIZED_STARUS'] == 'N') ? 'selected' : '' ?>>No</option>
                        </select>
                    </div>
                </div>

                <div class="mb-3">
                    <label>Address</label>
                    <input type="text" name="ORGANIZATION_ADDRESS" class="form-control"
                           value="<?= htmlspecialchars($editOrg['ORGANIZATION_ADDRESS'] ?? '') ?>">
                </div>

                <div class="mb-3">
                    <label>Contact</label>
                    <input type="text" name="ORGANIZATION_CONTACT" class="form-control"
                           value="<?= htmlspecialchars($editOrg['ORGANIZATION_CONTACT'] ?? '') ?>">
                </div>

                <button type="submit" class="btn btn-primary"><?= $editOrg ? 'Update' : 'Add Organization' ?></button>
                <?php if ($editOrg): ?>
                    <a href="add_org.php" class="btn btn-secondary">Cancel</a>
                <?php endif; ?>
            </form>
        </div>
    </div>
    <?php endif; ?>

    <!-- Organization Table -->
    <div class="table-responsive">
        <table class="table table-bordered table-striped align-middle">
            <thead class="table-dark">
                <tr>
                    <th>Org Code</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Contact</th>
                    <th>Authorized</th>
                    <th>Entry User</th>
                    <th>Entry Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($organizations as $org): ?>
                    <tr>
                        <td><?= htmlspecialchars($org['ORG_CODE']) ?></td>
                        <td><?= htmlspecialchars($org['ORGANIZATION_NAME']) ?></td>
                        <td><?= htmlspecialchars($org['ORGANIZATION_ADDRESS']) ?></td>
                        <td><?= htmlspecialchars($org['ORGANIZATION_CONTACT']) ?></td>
                        <td><?= htmlspecialchars($org['AUTHORIZED_STARUS']) ?></td>
                        <td><?= htmlspecialchars($org['ENTRY_USER']) ?></td>
                        <td><?= htmlspecialchars($org['ENTRY_DATE']) ?></td>
                        <td>
                            <?php if ($canEdit): ?>
                                <a href="?edit=<?= urlencode($org['ORG_CODE']) ?>" class="btn btn-sm btn-warning">Edit</a>
                            <?php endif; ?>
                            <?php if ($canDelete): ?>
                                <a href="?delete=<?= urlencode($org['ORG_CODE']) ?>" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure?')">Delete</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>

<?php include 'footer.php'; ?>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
