<?php
session_start();
require 'db.php';

// Ensure user is logged in
if (!isset($_SESSION['user'])) {
    header("Location: login.php");
    exit();
}

// Logged-in user info
$user    = $_SESSION['user'];
$orgCode = $user['org_code'];
$brCode  = $user['br_code'];   // ✅ BRANCH CODE ADDED

// Fetch organization details
$orgStmt = $pdo->prepare("
    SELECT ORGANIZATION_NAME, ORGANIZATION_ADDRESS 
    FROM organization_info 
    WHERE ORG_CODE = :org_code
");
$orgStmt->execute(['org_code' => $orgCode]);
$org = $orgStmt->fetch(PDO::FETCH_ASSOC);

$orgName    = $org['ORGANIZATION_NAME'] ?? 'Organization';
$orgAddress = $org['ORGANIZATION_ADDRESS'] ?? '';

// Fetch stock report (ORG + BRANCH wise)
$stockStmt = $pdo->prepare("
    SELECT 
        product_category_name, 
        supplier_name,
        SUM(remaining) AS total_quantity
    FROM stock_details_view
    WHERE org_code = :org_code
      AND br_code  = :br_code
    GROUP BY product_category_name, supplier_name
    ORDER BY product_category_name, supplier_name
");

$stockStmt->execute([
    'org_code' => $orgCode,
    'br_code'  => $brCode
]);

$stockData = $stockStmt->fetchAll(PDO::FETCH_ASSOC);

include 'header.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Stock Report - <?= htmlspecialchars($orgName) ?></title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
body { background:#f8f9fa; margin:20px; }
.report-container { background:#fff; padding:20px; border-radius:6px; }

.table thead { background:#343a40; color:#fff; }
.table tfoot { background:#e9ecef; font-weight:bold; }

.no-print { margin-bottom:20px; }
.print-header, .print-footer { display:none; }

@media print {

    @page {
        margin: 1.5cm;
    }

    body {
        background:#fff !important;
    }

    header, footer, nav, .no-print, .btn, #stockSearch {
        display:none !important;
    }

    .print-header {
        display:block !important;
        text-align:center;
        margin-bottom:20px;
    }

    .print-footer {
        display:block !important;
        position:fixed;
        bottom:0;
        width:100%;
        text-align:center;
        font-size:10px;
        color:#777;
        border-top:1px solid #ddd;
        padding-top:5px;
    }

    .table-responsive { overflow:visible !important; }
}
</style>
</head>

<body>

<div class="container report-container">

    <!-- SEARCH & PRINT -->
    <div class="row mb-3 no-print">
        <div class="col-md-4">
            <input type="text" id="stockSearch" class="form-control"
                   placeholder="Search Category/Supplier..."
                   onkeyup="searchStockTable()">
        </div>
        <div class="col-md-8 text-end">
            <button class="btn btn-success" onclick="window.print()">Print Report</button>
        </div>
    </div>

    <!-- PRINT HEADER -->
    <div class="print-header">
        <h2><?= htmlspecialchars($orgName) ?></h2>
        <h5><?= htmlspecialchars($orgAddress) ?></h5>
        <h4 class="text-secondary">Stock Status Report</h4>
        <p>
            Branch Code: <?= htmlspecialchars($brCode) ?> |
            <?= date('d M Y, H:i') ?>
        </p>
        <hr>
    </div>

    <!-- TABLE -->
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover" id="stockTable">
            <thead>
                <tr>
                    <th style="width:60px;">SL</th>
                    <th>Product Category</th>
                    <th>Supplier Name</th>
                    <th class="text-end">Total Quantity</th>
                </tr>
            </thead>
            <tbody>
            <?php
            $sl = 1;
            foreach ($stockData as $row):
            ?>
                <tr>
                    <td class="sl"><?= $sl++ ?></td>
                    <td><?= htmlspecialchars($row['product_category_name']) ?></td>
                    <td><?= htmlspecialchars($row['supplier_name']) ?></td>
                    <td class="text-end qty"><?= number_format($row['total_quantity'] ?? 0) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-end">Grand Total</td>
                    <td class="text-end" id="grandTotal">
                        <?= number_format(array_sum(array_column($stockData,'total_quantity'))) ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- PRINT FOOTER -->
    <div class="print-footer">
        Generated by Stock Management System
    </div>

</div>

<script>
function searchStockTable() {
    const filter = document.getElementById('stockSearch').value.toLowerCase();
    const rows = document.querySelectorAll('#stockTable tbody tr');

    let total = 0;
    let sl = 1;

    rows.forEach(row => {
        const text = row.innerText.toLowerCase();
        const qty  = parseFloat(row.querySelector('.qty').innerText.replace(/,/g,'')) || 0;

        if (text.includes(filter)) {
            row.style.display = '';
            row.querySelector('.sl').innerText = sl++;
            total += qty;
        } else {
            row.style.display = 'none';
        }
    });

    document.getElementById('grandTotal').innerText = total.toLocaleString();
}
</script>

<?php include 'footer.php'; ?>
</body>
</html>
